  
version: "3"
services:
  db:
    restart: on-failure
    image: postgres
    environment:
      - POSTGRES_PASSWORD=test
      - POSTGRES_USER=test
      - POSTGRES_DB=test
    ports:
      - "5432:5432"
    volumes:
      - "./docker-db-data:/var/lib/postgresql/data"

